version: '3'

services:
  nginx:
    build: ./nginx
    links:
      - server-john
      - server-paul
      - server-george
      - server-ringo
    ports:
      - "80:80"

  server-john:
    image: chat
    build: ./server
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=John

  server-paul:
    image: chat
    depends_on:
      - server-john
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Paul

  server-george:
    image: chat
    depends_on:
      - server-john
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=George

  server-ringo:
    image: chat
    depends_on:
      - server-john
    links:
      - redis
    expose:
      - "3000"
    environment:
      - NAME=Ringo

  redis:
    image: redis:alpine
    expose:
      - "6379"
